ip: \d{,3}\.\d{,3}\.\d{,3}\.\d{,3}
log_time: \d\d\/\w\w\w\/\d\d\d\d:\d\d:\d\d:\d\d \+\d\d\d\d
date_time_format: \%d/\%b/\%Y:\%H:\%M:\%S \%z
status_code: ' \d\d\d '
os: '(?:\d{,3}.\d{,3}.\d{,3}.\d{,3}. - - \[\d\d\/\w\w\w\/\d\d\d\d:\d\d:\d\d:\d\d \+\d\d\d\d] \"\w{3,4} \/[a-zA-Z/\ 0-9-.]*\" \d{3} \d+ \"[a-zA-Z:\/.\- 0-9]*\" \"[a-zA-Z0-9/\.]* \()([a-zA-Z0-9/-]*)'
browser:  '(?:\d{,3}.\d{,3}.\d{,3}.\d{,3}. - - \[\d\d\/\w\w\w\/\d\d\d\d:\d\d:\d\d:\d\d \+\d\d\d\d] \"\w{3,4} \/[a-zA-Z/\ 0-9-.]*\" \d{3} \d+ \"[a-zA-Z:\/.\- 0-9]*\" \")(\w*)'